### ISSUE TITLE
Add ok status and error message indication

### ISSUE THREAD

**Issue by tkurki** [preeve9534/signalk-tank-monitor#1]
You can indicate ok status and post on error message by using setProviderStatus and setProviderError messages in the plugin api: https://github.com/SignalK/signalk-server-node/blob/master/SERVERPLUGINS.md#appsetproviderstatusmsg

In this case missing rrdtool would be an error and if no errors are present and writing seems to work you could post OK status. Other possible errors that may crop up are running out of disk space or not having write access to the graph directory.

**Comment by tkurki** [comment]
Sorry; I had missed the setProvider calls. Just thought that people will struggle with rrdtool installation, assuming that just installing the plugin will work, so an explicit check & error status in case it is missing would be a good idea.

**Comment by preeve9534** [comment]
No worries.  I think the only obvious failure mode not already covered by reporting in some way was the absence of a check for rrdtool and I'm just about to push that.
